
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai
    password: 493658400
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl



#mybatis - plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.yr.springbootmybatisplus.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









